### ISSUE TITLE
Instant level completion

### ISSUE THREAD

**Issue by kieran154** [ashpemb/TGPSEM2#34]
Reproduction
- Level 2
- Press the right side of the start button

Consequences
- Player is able to complete level 2 almost instantly

Percentage
- 40%

Device
HTC Nexus & PC

![b149405c4c7f5a1f22c058d5e816aa1e](https://cloud.githubusercontent.com/assets/15891283/14326028/072577ae-fc24-11e5-9cc5-12144b259adb.gif)

**Comment by Flave229** [comment]
Could not replicate this issue. I have implemented a check when the Start Menu is clicked in order to potentially fix this. For now, I will close this issue.

**Comment by Malcom-Nubbins** [comment]
Reopening this as the issue is still present on mobile devices.
